# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ChampStats
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore

    - name: Publish
      run: dotnet publish ChampStats.fsproj -c Release --output ./Release

    - name: Upload app_Offline
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: ${{ secrets.FTP_SERVER }}
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        localDir: ./AppOffline/

    - name: Wait for 10 seconds
      run: sleep 10

    - name: Upload site
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: ${{ secrets.FTP_SERVER }}
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        localDir: ./ChampStats/Release/

    - name: Wait for 10 seconds
      run: sleep 10

    # - name: Remove app_Offline
    #   uses: StephanThierry/ftp-delete-action@v2.1
    #   with:
    #     host: ${{ secrets.FTP_SERVER }}
    #     user: ${{ secrets.FTP_USERNAME }}
    #     password: ${{ secrets.FTP_PASSWORD }}
    #     remoteFiles: "app_offline.htm"
    #     ignoreSSL: "1"

    - name: Remove app_Offline
      shell: python
      run: |
        import ftplib
        with FTP('${{ secrets.FTP_SERVER }}') as ftp:
          ftp.login('${{ secrets.FTP_USERNAME }}', '${{ secrets.FTP_PASSWORD }}')
          ftp.delete('app_offline.htm')


